# Generated by Django 4.0.4 on 2022-05-08 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0002_project_category_project_desc_project_img_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='collab',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='collab_link',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='country',
            field=models.CharField(default='UNKNOWN', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='website_link',
            field=models.CharField(default='UNKNOWN', max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='desc',
            field=models.TextField(default='UNKNOWN'),
        ),
        migrations.AlterField(
            model_name='project',
            name='short_desc',
            field=models.TextField(default='UNKNOWN'),
        ),
    ]
